# Don't change this! Version used to track needed updates.
version = 0
disable_player_attribute_screen = false
use_attribute_screen_configuration_from_server = false
attribute_screen_configuration = [
    "STRING:gui.attribute_screen.attributes",
    "EMPTY_LINE",
    "ATTRIBUTE_VALUE:minecraft:generic.max_health",
    "STRING_REQUIRES_ATTRIBUTE:gui.attribute_screen.health_regeneration_line_1:healthregenerationoverhaul:generic.health_regeneration",
    "CUSTOM_ATTRIBUTE_VALUE:gui.attribute_screen.health_regeneration_line_2:healthregenerationoverhaul:generic.health_regeneration",
    "ATTRIBUTE_VALUE:manaattributes:generic.max_mana",
    "STRING_REQUIRES_ATTRIBUTE:gui.attribute_screen.mana_regeneration_line_1:manaattributes:generic.mana_regeneration",
    "CUSTOM_ATTRIBUTE_VALUE:gui.attribute_screen.mana_regeneration_line_2:manaattributes:generic.mana_regeneration",
    "ATTRIBUTE_VALUE:staminaattributes:generic.max_stamina",
    "STRING_REQUIRES_ATTRIBUTE:gui.attribute_screen.stamina_regeneration_line_1:staminaattributes:generic.stamina_regeneration",
    "CUSTOM_ATTRIBUTE_VALUE:gui.attribute_screen.stamina_regeneration_line_2:staminaattributes:generic.stamina_regeneration",
    "ATTRIBUTE_VALUE:minecraft:generic.armor",
    "STRING_REQUIRES_ATTRIBUTE:gui.attribute_screen.armor_toughness_line_1:minecraft:generic.armor_toughness",
    "CUSTOM_ATTRIBUTE_VALUE:gui.attribute_screen.armor_toughness_line_2:minecraft:generic.armor_toughness",
    "ATTRIBUTE_VALUE:minecraft:generic.luck"
]