#Whether to start the mod enabled
startHibernated = true
#Ticks to skip during hibernation
#Range: 1 ~ 9223372036854775807
ticksToSkip = 1000
#Permission level needed to execute commands
#Range: 0 ~ 4
permissionLevel = 2

